apiVersion: v1
kind: Service
metadata:
  name: signup-manager-service
spec:
  selector:
    app: signup-manager
  type: NodePort
  ports:
    - port: 5051
      targetPort: 5051
      nodePort: 30005
